{
    "image": "finally_catches_exception.png",
    "date": "2024-01-12",
    "title": "Finally Catches Exception",
    "content": "In this code, finally is executed after the throw. Since it contains a return, the function is finalized before the throw is executed. The exception is then lost, and the scripts displays 1. This is why it is recommended to avoid return in a finally clause.",
    "seeAlso": {
        "Finally (PHP manual)": "https://www.php.net/manual/en/language.exceptions.php#language.exceptions.finally"
    },
    "tags": [
    "edge case"
    ],
    "author": "",
    "contact": "",
    "3v4l": {
        "Catch an exception with finally": "https://3v4l.org/uVRJ3"
    },
    "phpError": {},
    "features": [        
        "finally",
        "return"
]
}